# nixpacks.toml

[phases.setup]
nixPkgs = ["php82", "nodejs_20", "chromium", "chromedriver"]

[phases.build]
cmds = ["npm install", "npm run build", "composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan storage:link && php artisan migrate --force && php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT"