# nixpacks.toml

[phases.setup]
# GANTI "composer" JADI "php82Packages.composer"
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20", "chromium", "chromedriver", "git", "unzip"]

[phases.build]
cmds = ["npm install", "npm run build", "composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan storage:link && php artisan migrate --force && php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT"